// <auto-generated />
namespace cfab.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class datetypeid : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(datetypeid));
        
        string IMigrationMetadata.Id
        {
            get { return "201702082103420_datetypeid"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
